<?php

return [
    'online' => 'متصل',
    'offline' => 'غير متصل',
    'starting' => 'يبدأ',
    'stopping' => 'يتوقف',
    'suspended' => 'معلق',
    'connection-error' => 'خطأ في الإتصال',
    'transferring' => 'انتقال',
    'installing' => 'يتم التثبيت',
    'restoring-backup' => 'استعادة النسخة الاحتياطية',
    'unavailable' => 'غير متاح',
    'status' => 'الحالة',
    'CPU' => 'CPU',
    'memory' => 'الذاكرة',
    'disk' => 'التخزين',
    'unlimited' => 'غير محدود',
    'start' => 'يبدا',
    'restart' => 'إعادة تشغيل',
    'stop' => 'توقف',
    'kill' => 'قتل',
    'forcibly-stop-process' => 'إيقاف العملية بالقوة',
    'continue' => 'يكمل',
    'forcibly-stopping-alert' => 'يمكن أن يؤدي إيقاف الخادم بالقوة إلى تلف البيانات.',
    'cpu-usage' => 'CPU استخدام',
    'memory-usage' => 'استخدام الذاكرة',
    'disk-usage' => 'إستخدام التخزين',
    'inbound-outbound' => 'واردة / صادرة',
    'low-resources' => 'منخفضة في الموارد',
    'low-resources-desc' => 'موارد الخادم الخاص بك منخفضة، تأكد من ترقية خطتك',
    'upgrade-server' => 'ترقية الخادم',
    'cancel' => 'إلغاء',
    'copied-text' => 'تم نسخ {{text}} إلى الحافظة.',
    'showing' => 'عرض',
    'to' => 'إلى',
    'of' => 'من',
    'results' => 'النتائج.',
];
